config/routes.rb
Rails3MongoidDevise::Application.routes.draw do

  devise_for :users
  resources :users do
    resources :todolists
  end

  root :to => 'todolists#index'

end

app/models/todolist.rb
class Todolist
  include Mongoid::Document

  field :description, type: String
  field :priority, type: Integer
  
  ####belongs_to :user
  embedded_in :user

  validates :description, :priority, :presence => true

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  field :name,    type: String
  
  index({ name: 1 }, { unique: true })
  
  ####has_many :todolists
  embeds_many :todolists
  
  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery
  	respond_to :html, :json
  	before_filter :authenticate_user!

  	private
  	def set_flash_message(message, type)
    	flash[type.to_sym] = message
  	end

end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
    def index
        @todolists = current_user.todolists
    end

    def show
        @todolist = get_todolist(params[:id])
    end

    def new
        @todolist = current_user.todolists.new
    end

    def edit
        @todolist = get_todolist(params[:id])
    end

    def create
        @todolist = current_user.todolists.new(params[:todolist])
        set_flash_message('Todolist was successfully created.','notice') if @todolist.save
        respond_with(current_user, @todolist)
    end

    def update
        @todolist = get_todolist(params[:id])
        set_flash_message('Todolist was successfully updated.','notice') if @todolist.update_attributes(params[:todolist])
        respond_with(current_user, @todolist)
    end

    def destroy
        @todolist = get_todolist(params[:id])
        set_flash_message('Todolist was successfully deleted.','notice') if @todolist.destroy
        respond_with(current_user, @todolist)
    end

    private
    def get_todolist(todolist_id)
        current_user.todolists.find(todolist_id) rescue redirect_to root_path, alert: "Not found."
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3MongoidDevise</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>

<br/>

<p id="notice"><%= notice %></p>
<p id="error" style="color:red;"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/todolists/_form.html.erb
<%= form_for([current_user, @todolist]) do |t| %>

  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% @todolist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= t.label :description %><br />
    <%= t.text_field :description %>
  </div>
  <div class="field">
    <%= t.label :priority %><br />
    <%= t.number_field :priority %>
  </div>
  <div class="actions">
    <%= t.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', user_todolist_path(current_user, @todolist) %>|
<%= link_to 'Back', user_todolists_path %>

app/views/todolists/index.html.erb
<h1>Listing todolists</h1>

<table>
  <tr>
    <th>Description</th>
    <th>User</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todolists.each do |todolist| %>
  <tr>
    <td><%= todolist.description %></td>
    <td><%= todolist.user.email %></td>
    <td><%= todolist.priority %></td>

    <td><%= link_to 'Show', user_todolist_path(current_user, todolist) %></td>
    <td><%= link_to 'Edit', edit_user_todolist_path(current_user, todolist) %></td>
    <td><%= link_to 'Destroy', [current_user, todolist], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
    
<br />

<%= link_to 'New Todolist', new_user_todolist_path(current_user) %>

app/views/todolists/new.html.erb
<h1>New todolist</h1>

<%= render 'form' %>

<%= link_to 'Back', user_todolists_path %>

app/views/todolists/show.html.erb
<p>
  <b>Description:</b>
  <%= @todolist.description %>
</p>

<p>
  <b>User:</b>
  <%= @todolist.user.email %>
</p>

<p>
  <b>Priority:</b>
  <%= @todolist.priority %>
</p>

<%= link_to 'Edit', edit_user_todolist_path(current_user, @todolist) %> |
<%= link_to 'Back', user_todolists_path %>